name: CI/CD Pipeline

on:
  push:
    branches: ['master', 'feat/**']

env:
  VITE_RIDDLE_API_KEY: ${{ secrets.RIDDLE_API_KEY }}

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Upload code coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage/

  build_deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      TAG: 0.1.${{ github.run_number }}
    needs: [test]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cryper:${TAG} .

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Publish Docker
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cryper:${TAG}
